import { STATIC } from "~/playground";

export default {
	heading: "Products",
	categories: ["Category 1", "Category 2", "Category 3", "Category 4"],
	items: [
		[
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "ad",
				heading: "Product delivery",
				subheading: "Learn all about how we deliver your products.",
				link: "#",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
		],
		[
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "ad",
				heading: "Product delivery",
				subheading: "Learn all about how we deliver your products.",
				link: "#",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
		],
		[
			{
				type: "ad",
				heading: "Product delivery",
				subheading: "Learn all about how we deliver your products.",
				link: "#",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
		],
		[
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "ad",
				heading: "Product delivery",
				subheading: "Learn all about how we deliver your products.",
				link: "#",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
			{
				type: "product",
				name: "Jeans",
				image: `${STATIC}/images/planets/Saturn.jpeg`,
				price: "40$",
				description: "Best jeans from GreatSimple",
			},
		],
	],
};
