import { STATIC } from "~/playground";

export default [
	[
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "ad",
			heading: "Product delivery",
			subheading: "Learn all about how we deliver your products.",
			link: "#",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
	],
	[
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "ad",
			heading: "Product delivery",
			subheading: "Learn all about how we deliver your products.",
			link: "#",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
	],
	[
		{
			type: "ad",
			heading: "Product delivery",
			subheading: "Learn all about how we deliver your products.",
			link: "#",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
	],
	[
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "ad",
			heading: "Product delivery",
			subheading: "Learn all about how we deliver your products.",
			link: "#",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
		{
			type: "product",
			name: "Jeans",
			image: `${STATIC}/images/planets/Saturn.jpeg`,
			price: "40$",
			description: "Best jeans from GreatSimple",
		},
	],
];
